name: Five Tree Wood AI
version: "1.0.0"
slug: five_tree_wood_ai
description: AI-powered aircon temperature prediction for Home Assistant
url: https://github.com/pennyw00d/five-tree-wood-ai
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
init: false
map:
  - "share:rw"
  - "ssl"
options:
  influxdb_url: "http://influxdb.ninjateaparty:8086"
  influxdb_org: "Ninjateaparty"
  influxdb_bucket: "homeassistant"
  log_level: "info"
  api_port: 8099
schema:
  influxdb_url: str
  influxdb_token: password
  influxdb_org: str
  influxdb_bucket: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  api_port: port?
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Five Tree Wood AI REST API
#image: ghcr.io/Swamp-Ig/five-tree-wood-ai-{arch}
